/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author MI AL ISHLAH
 */
public class AboutUsPage extends javax.swing.JPanel {

    /**
     * Creates new form AboutUsPage
     */
    public AboutUsPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        marsya = new javax.swing.JPanel();
        nimNama1 = new javax.swing.JLabel();
        ariq = new javax.swing.JPanel();
        nimNama2 = new javax.swing.JLabel();
        farid = new javax.swing.JPanel();
        nimNama3 = new javax.swing.JLabel();
        adisya = new javax.swing.JPanel();
        nimNama4 = new javax.swing.JLabel();
        naufal = new javax.swing.JPanel();
        nimNama5 = new javax.swing.JLabel();
        erwin = new javax.swing.JPanel();
        nimNama6 = new javax.swing.JLabel();
        prev = new javax.swing.JLabel();
        next = new javax.swing.JLabel();
        aboutUs = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marsya.setPreferredSize(new java.awt.Dimension(180, 160));
        marsya.setLayout(new java.awt.CardLayout());
        mainPanel.add(marsya, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        nimNama1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/10122241 MARSYA AWLIYA SABRINA.png"))); // NOI18N
        mainPanel.add(nimNama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        ariq.setPreferredSize(new java.awt.Dimension(180, 160));
        ariq.setLayout(new java.awt.CardLayout());
        mainPanel.add(ariq, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        nimNama2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/10122254 ARIQ HIKARI HIDAYAT.png"))); // NOI18N
        mainPanel.add(nimNama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        farid.setPreferredSize(new java.awt.Dimension(180, 160));
        farid.setLayout(new java.awt.CardLayout());
        mainPanel.add(farid, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, -1, -1));

        nimNama3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/10122256 MUHAMMAD FARID NURRAHMAN.png"))); // NOI18N
        mainPanel.add(nimNama3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, -1, -1));

        adisya.setPreferredSize(new java.awt.Dimension(180, 160));
        adisya.setLayout(new java.awt.CardLayout());
        mainPanel.add(adisya, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));

        nimNama4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/10122260 ADISYA AINUN FATIHAH.png"))); // NOI18N
        mainPanel.add(nimNama4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, -1, -1));

        naufal.setPreferredSize(new java.awt.Dimension(180, 160));
        naufal.setLayout(new java.awt.CardLayout());
        mainPanel.add(naufal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        nimNama5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/10122264 MUHAMMAD NAUFAL GHIFARI.png"))); // NOI18N
        mainPanel.add(nimNama5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 630, -1, -1));

        erwin.setPreferredSize(new java.awt.Dimension(180, 160));
        erwin.setLayout(new java.awt.CardLayout());
        mainPanel.add(erwin, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, -1, -1));

        nimNama6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/10122269 ERWIN HAFIZ TRIADI.png"))); // NOI18N
        mainPanel.add(nimNama6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 630, -1, -1));

        prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Arrow Left.png"))); // NOI18N
        mainPanel.add(prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, -1, -1));

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Arrow Right.png"))); // NOI18N
        mainPanel.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 30, -1, -1));

        aboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fq.png"))); // NOI18N
        mainPanel.add(aboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/descfilm.png"))); // NOI18N
        mainPanel.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutUs;
    private javax.swing.JPanel adisya;
    private javax.swing.JPanel ariq;
    private javax.swing.JLabel background;
    private javax.swing.JPanel erwin;
    private javax.swing.JPanel farid;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel marsya;
    private javax.swing.JPanel naufal;
    private javax.swing.JLabel next;
    private javax.swing.JLabel nimNama1;
    private javax.swing.JLabel nimNama2;
    private javax.swing.JLabel nimNama3;
    private javax.swing.JLabel nimNama4;
    private javax.swing.JLabel nimNama5;
    private javax.swing.JLabel nimNama6;
    private javax.swing.JLabel prev;
    // End of variables declaration//GEN-END:variables
}
