/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JPanel;

/**
 *
 * @author ariqhikari
 */
public class DetailMoviePage extends javax.swing.JPanel {

    /**
     * Creates new form DetailMoviePage
     */
    public DetailMoviePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDetailMovie = new javax.swing.JPanel();
        jLabelStar4 = new javax.swing.JLabel();
        jLabelStar3 = new javax.swing.JLabel();
        jLabelStar2 = new javax.swing.JLabel();
        jLabelStar1 = new javax.swing.JLabel();
        jLabelStar = new javax.swing.JLabel();
        jLabelRating = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();
        jLabelLine = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        bgAge = new javax.swing.JLabel();
        labelAge = new javax.swing.JLabel();
        jLabelSutradara = new javax.swing.JLabel();
        labelSutradara = new javax.swing.JLabel();
        labelDurasi = new javax.swing.JLabel();
        jLabelGenre1 = new javax.swing.JLabel();
        labelGenre = new javax.swing.JLabel();
        jLabelGenre = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        labelTanggalRilis = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelPoster = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabelBg = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        panelDetailMovie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelStar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star.png"))); // NOI18N
        panelDetailMovie.add(jLabelStar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, -1, -1));

        jLabelStar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star-fill.png"))); // NOI18N
        panelDetailMovie.add(jLabelStar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        jLabelStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star-fill.png"))); // NOI18N
        panelDetailMovie.add(jLabelStar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, -1));

        jLabelStar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star-fill.png"))); // NOI18N
        panelDetailMovie.add(jLabelStar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, -1, -1));

        jLabelStar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star-fill.png"))); // NOI18N
        panelDetailMovie.add(jLabelStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, -1));

        jLabelRating.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        jLabelRating.setForeground(new java.awt.Color(252, 255, 86));
        jLabelRating.setText("8.8");
        panelDetailMovie.add(jLabelRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabelDescription.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabelDescription.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescription.setText("Description Movie");
        panelDetailMovie.add(jLabelDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, -1, -1));
        jLabelDescription.setText("<HTML>Berkisah tentang kehidupan para Barbie yang memiliki karakter berbeda-beda. Semua perempuan dipanggil Barbie dan laki-laki dipanggil Ken, tetapi mereka dapat saling mengenal.</HTML>");

        jLabelLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/line-description.png"))); // NOI18N
        panelDetailMovie.add(jLabelLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, -1, 10));

        jLabelAge.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelAge.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAge.setText("R 13+");
        panelDetailMovie.add(jLabelAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, -1, -1));

        bgAge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg-rating.png"))); // NOI18N
        panelDetailMovie.add(bgAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        labelAge.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        labelAge.setForeground(new java.awt.Color(255, 255, 255));
        labelAge.setText("Rating Usia");
        panelDetailMovie.add(labelAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        jLabelSutradara.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelSutradara.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSutradara.setText("Greta Gerwig");
        panelDetailMovie.add(jLabelSutradara, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        labelSutradara.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        labelSutradara.setForeground(new java.awt.Color(255, 255, 255));
        labelSutradara.setText("Sutradara");
        panelDetailMovie.add(labelSutradara, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        labelDurasi.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        labelDurasi.setForeground(new java.awt.Color(255, 255, 255));
        labelDurasi.setText("Durasi");
        panelDetailMovie.add(labelDurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        jLabelGenre1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelGenre1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenre1.setText("1 Jam 54 Menit");
        panelDetailMovie.add(jLabelGenre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        labelGenre.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        labelGenre.setForeground(new java.awt.Color(255, 255, 255));
        labelGenre.setText("Genre");
        panelDetailMovie.add(labelGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jLabelGenre.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelGenre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenre.setText("Adventure, Comedy, Fantasy");
        panelDetailMovie.add(jLabelGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        jLabelDate.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDate.setText("19 Juli 2023 (Indonesia)");
        panelDetailMovie.add(jLabelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));

        labelTanggalRilis.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        labelTanggalRilis.setForeground(new java.awt.Color(255, 255, 255));
        labelTanggalRilis.setText("Tanggal Liris");
        panelDetailMovie.add(labelTanggalRilis, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        jLabelTitle.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("BARBIE");
        panelDetailMovie.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        jLabelPoster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/poster-movie.jpeg"))); // NOI18N
        panelDetailMovie.add(jLabelPoster, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N
        panelDetailMovie.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg-description.png"))); // NOI18N
        panelDetailMovie.add(jLabelBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(panelDetailMovie, "card2");
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getPanelDetailMovie() {
        return panelDetailMovie;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgAge;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelBg;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelGenre;
    private javax.swing.JLabel jLabelGenre1;
    private javax.swing.JLabel jLabelLine;
    private javax.swing.JLabel jLabelPoster;
    private javax.swing.JLabel jLabelRating;
    private javax.swing.JLabel jLabelStar;
    private javax.swing.JLabel jLabelStar1;
    private javax.swing.JLabel jLabelStar2;
    private javax.swing.JLabel jLabelStar3;
    private javax.swing.JLabel jLabelStar4;
    private javax.swing.JLabel jLabelSutradara;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelDurasi;
    private javax.swing.JLabel labelGenre;
    private javax.swing.JLabel labelSutradara;
    private javax.swing.JLabel labelTanggalRilis;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelDetailMovie;
    // End of variables declaration//GEN-END:variables
}
