/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author mfari
 */
public class HistoryTicketPage extends javax.swing.JPanel {

    /**
     * Creates new form HistoryTicketPage
     */
    public HistoryTicketPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHistory = new javax.swing.JPanel();
        jLabelCircleTop1 = new javax.swing.JLabel();
        jLabelCircleTop3 = new javax.swing.JLabel();
        jLabelCircleBottom4 = new javax.swing.JLabel();
        jLabelCircleBottom3 = new javax.swing.JLabel();
        jLabelCircleBottom2 = new javax.swing.JLabel();
        jLabelCircleBottom1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelStrips = new javax.swing.JLabel();
        jLabelGenre = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        star5 = new javax.swing.JLabel();
        star4 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        star1 = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelSeat = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelCode = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JLabel2 = new javax.swing.JLabel();
        jLabelMenu = new javax.swing.JLabel();
        JLabelBg = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 800));
        setLayout(new java.awt.CardLayout());

        jPanelHistory.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHistory.setMaximumSize(new java.awt.Dimension(1200, 32767));
        jPanelHistory.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanelHistory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCircleTop1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/circle-top.png"))); // NOI18N
        jPanelHistory.add(jLabelCircleTop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 85, -1, -1));

        jLabelCircleTop3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/circle-top.png"))); // NOI18N
        jPanelHistory.add(jLabelCircleTop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 85, -1, -1));

        jLabelCircleBottom4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/circle-bottom.png"))); // NOI18N
        jPanelHistory.add(jLabelCircleBottom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 740, -1, -1));

        jLabelCircleBottom3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/circle-bottom.png"))); // NOI18N
        jPanelHistory.add(jLabelCircleBottom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 740, -1, -1));

        jLabelCircleBottom2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/circle-bottom.png"))); // NOI18N
        jPanelHistory.add(jLabelCircleBottom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 740, -1, -1));

        jLabelCircleBottom1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/circle-bottom.png"))); // NOI18N
        jLabelCircleBottom1.setPreferredSize(new java.awt.Dimension(60, 62));
        jPanelHistory.add(jLabelCircleBottom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 740, -1, -1));

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));
        jPanel1.setPreferredSize(new java.awt.Dimension(505, 730));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelStrips.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabelStrips.setText("----------------------------------");
        jPanel1.add(jLabelStrips, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 540, -1));

        jLabelGenre.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabelGenre.setText("Adventure, Comedy, Fantasy");
        jPanel1.add(jLabelGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 90, 390, -1));

        jLabelTitle.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        jLabelTitle.setText("BARBIE");
        jPanel1.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 40, -1, -1));

        star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star.png"))); // NOI18N
        jPanel1.add(star5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star.png"))); // NOI18N
        jPanel1.add(star4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star.png"))); // NOI18N
        jPanel1.add(star3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star.png"))); // NOI18N
        jPanel1.add(star2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/star.png"))); // NOI18N
        jPanel1.add(star1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabelStatus.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(255, 51, 51));
        jLabelStatus.setText("Success");
        jPanel1.add(jLabelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 130, -1));

        jPanel2.setBackground(new java.awt.Color(190, 185, 185));
        jPanel2.setPreferredSize(new java.awt.Dimension(505, 280));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel2.setText("IDR 80.000");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 280, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel7.setText("TIMI");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 80, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel8.setText("Name :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel9.setText("Paid :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 60, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel3.setText("Seat & Numbers");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 180, -1));

        jLabelSeat.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabelSeat.setText("E5, E6");
        jPanel1.add(jLabelSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 260, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Status");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 70, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel6.setText("Transaction Code");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, -1));

        jLabelCode.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabelCode.setText("CODE-980864");
        jPanel1.add(jLabelCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 270, -1));

        jLabelDate.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabelDate.setText("Senin, 01 Juli 2023");
        jPanel1.add(jLabelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 270, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel4.setText("Date & Time");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, -1));

        jPanelHistory.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 45, -1, -1));

        JLabel2.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        JLabel2.setForeground(new java.awt.Color(255, 255, 255));
        JLabel2.setText("NOW PLAYING");
        jPanelHistory.add(JLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 170, -1));

        jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-menu.png"))); // NOI18N
        jPanelHistory.add(jLabelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 25, -1, -1));

        JLabelBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg-beranda.png"))); // NOI18N
        jPanelHistory.add(JLabelBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 820));

        add(jPanelHistory, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel2;
    private javax.swing.JLabel JLabelBg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCircleBottom1;
    private javax.swing.JLabel jLabelCircleBottom2;
    private javax.swing.JLabel jLabelCircleBottom3;
    private javax.swing.JLabel jLabelCircleBottom4;
    private javax.swing.JLabel jLabelCircleTop1;
    private javax.swing.JLabel jLabelCircleTop3;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelGenre;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelSeat;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelStrips;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelHistory;
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    private javax.swing.JLabel star4;
    private javax.swing.JLabel star5;
    // End of variables declaration//GEN-END:variables
}
