/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author ariqhikari
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabelLogin = new javax.swing.JLabel();
        gradientUsername = new elements.Gradient();
        txtUsername = new elements.TextField();
        gradientPassword = new elements.Gradient();
        txtPassword = new elements.TextField();
        jLabelPassword = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelBg = new javax.swing.JLabel();
        jLabelRectangle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(0, 25, 83));
        mainPanel.setMinimumSize(new java.awt.Dimension(500, 300));
        mainPanel.setPreferredSize(new java.awt.Dimension(1200, 800));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Login.png"))); // NOI18N
        mainPanel.add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, -1, -1));

        gradientUsername.setkEndColor(new java.awt.Color(141, 225, 243));
        gradientUsername.setkStartColor(new java.awt.Color(109, 218, 247));
        gradientUsername.setLayout(new java.awt.CardLayout());

        txtUsername.setPreferredSize(new java.awt.Dimension(310, 57));
        gradientUsername.add(txtUsername, "card2");

        mainPanel.add(gradientUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        gradientPassword.setkEndColor(new java.awt.Color(141, 225, 243));
        gradientPassword.setkStartColor(new java.awt.Color(109, 218, 247));
        gradientPassword.setLayout(new java.awt.CardLayout());

        txtPassword.setPreferredSize(new java.awt.Dimension(310, 57));
        gradientPassword.add(txtPassword, "card2");

        mainPanel.add(gradientPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        jLabelPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Password.png"))); // NOI18N
        mainPanel.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        jLabelUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Username.png"))); // NOI18N
        mainPanel.add(jLabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        jLabelDescription.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/description.png"))); // NOI18N
        mainPanel.add(jLabelDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jLabelTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/FIVE CINEMA.png"))); // NOI18N
        mainPanel.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabelLogo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N
        mainPanel.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabelBg.setBackground(new java.awt.Color(0, 25, 83));
        jLabelBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg-login.png"))); // NOI18N
        mainPanel.add(jLabelBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelRectangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rectangle-login.png"))); // NOI18N
        mainPanel.add(jLabelRectangle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private elements.Gradient gradientPassword;
    private elements.Gradient gradientUsername;
    private javax.swing.JLabel jLabelBg;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelRectangle;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel mainPanel;
    private elements.TextField txtPassword;
    private elements.TextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
