/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author erwin
 */
public class PembayaranPage extends javax.swing.JPanel {

    /**
     * Creates new form PembayaranView
     */
    public PembayaranPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new elements.TextField();
        textField2 = new elements.TextField();
        textField3 = new elements.TextField();
        textField4 = new elements.TextField();
        panelRound2 = new elements.PanelRound();
        jLabelHitung = new javax.swing.JLabel();
        jLabelDetailPemblian = new javax.swing.JLabel();
        jLabelTunai = new javax.swing.JLabel();
        jLabelKembalian = new javax.swing.JLabel();
        jLabelTotalHarga = new javax.swing.JLabel();
        panelRound5 = new elements.PanelRound();
        jLabelPrintTiket = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textField1.setBackground(new java.awt.Color(109, 218, 247));
        textField1.setRound(50);
        textField1.setShadowColor(new java.awt.Color(141, 225, 243));
        add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 667, 71));

        textField2.setBackground(new java.awt.Color(109, 218, 247));
        textField2.setRound(50);
        textField2.setShadowColor(new java.awt.Color(141, 225, 243));
        add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 667, 71));

        textField3.setBackground(new java.awt.Color(109, 218, 247));
        textField3.setRound(50);
        textField3.setShadowColor(new java.awt.Color(141, 225, 243));
        add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 667, 71));

        textField4.setBackground(new java.awt.Color(109, 218, 247));
        textField4.setRound(50);
        textField4.setShadowColor(new java.awt.Color(141, 225, 243));
        add(textField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 667, 71));

        panelRound2.setBackground(new java.awt.Color(251, 99, 199));
        panelRound2.setRoundBottomLeft(40);
        panelRound2.setRoundBottomRight(40);
        panelRound2.setRoundTopLeft(40);
        panelRound2.setRoundTopRight(40);
        panelRound2.setLayout(new java.awt.GridBagLayout());

        jLabelHitung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Hitung.png"))); // NOI18N
        panelRound2.add(jLabelHitung, new java.awt.GridBagConstraints());

        add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, 204, 71));

        jLabelDetailPemblian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Detail Pembelian (1).png"))); // NOI18N
        add(jLabelDetailPemblian, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 269, 80));

        jLabelTunai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Tunai (1).png"))); // NOI18N
        add(jLabelTunai, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 110, 60));

        jLabelKembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Kembalian (1).png"))); // NOI18N
        add(jLabelKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 170, 60));

        jLabelTotalHarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Total Harga (1).png"))); // NOI18N
        add(jLabelTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 210, 60));

        panelRound5.setBackground(new java.awt.Color(251, 99, 199));
        panelRound5.setRoundBottomLeft(40);
        panelRound5.setRoundBottomRight(40);
        panelRound5.setRoundTopLeft(40);
        panelRound5.setRoundTopRight(40);
        panelRound5.setLayout(new java.awt.GridBagLayout());

        jLabelPrintTiket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Print Tiket.png"))); // NOI18N
        panelRound5.add(jLabelPrintTiket, new java.awt.GridBagConstraints());

        add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 204, 71));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg-beranda.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 820));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabelDetailPemblian;
    private javax.swing.JLabel jLabelHitung;
    private javax.swing.JLabel jLabelKembalian;
    private javax.swing.JLabel jLabelPrintTiket;
    private javax.swing.JLabel jLabelTotalHarga;
    private javax.swing.JLabel jLabelTunai;
    private elements.PanelRound panelRound2;
    private elements.PanelRound panelRound5;
    private elements.TextField textField1;
    private elements.TextField textField2;
    private elements.TextField textField3;
    private elements.TextField textField4;
    // End of variables declaration//GEN-END:variables
}
